### ISSUE TITLE
cluster

### ISSUE THREAD

**Issue by FrankCAN** [WXinlong/ASIS#13]
Hi,
Thanks for your impressive work, but I just wonder why you set cluster number to 5 for instance segmentation, and what does this value mean? Thanks a lot.

net_ins = tf_util.conv1d(net_ins, **5**, 1, padding='VALID', activation_fn=None, scope='ins_fc4')

Best Regards
Frank

**Comment by WXinlong** [comment]
Hi, here the 5 is the dimention of instance embeddings, not cluster number. It means that each point is represented by a 5-dim vector, as its instance embedding.
