### ISSUE TITLE
Helping me,please.

### ISSUE THREAD

**Issue by renhaha123** [WXinlong/ASIS#17]
Thank you for your great work! I run the collect_indoor3d_data.py of ASIS-master ,but it didn't generate the Area_5_hallway_6.npy file.
  Could you please tell me  how to fix manually the Area_5/hallway_6 data?
  Thanks for your help.

**Comment by WXinlong** [comment]
Hi, please refer to [here](https://github.com/charlesq34/pointnet/issues/45#issuecomment-329261523) for detail:).
