### ISSUE TITLE
Instance segmentation annotations  for ShapeNet dataset

### ISSUE THREAD

**Issue by mohuamuyu** [WXinlong/ASIS#18]
Thank you for your great work!  Could you provide me a link to the ShapeNet dataset with instance segmentation annotations. If you can help me, It Will Be Really Nice Of You!

**Comment by WXinlong** [comment]
Hi, here is the [link](https://drive.google.com/drive/folders/192AN8JyTIfw2r3PLg52oCVZNnT-rXbDM) provided by the authors of SGPN:)
