### ISSUE TITLE
Performance on outdoor datasets

### ISSUE THREAD

**Issue by mzahran001** [WXinlong/ASIS#2]
I was wondering if you tried to test the **ASIS** on Outdoor dataset like KITTI or Semantic3D.

**Comment by WXinlong** [comment]
We didn't try on them as there is no point-level annotation  for KITTI dataset and no instance label for Semantic3D dataset.

**Comment by ZhengdiYu** [comment]
> We didn't try on them as there is no point-level annotation for KITTI dataset and no instance label for Semantic3D dataset.

Hey, I think their is per-point instance label in semantic KITTI now.
