### ISSUE TITLE
Some question about BlockMerging.

### ISSUE THREAD

**Issue by MrCrazyCrab** [WXinlong/ASIS#20]
@WXinlong Thanks for sharing your work, and i have some question for the function of BlockMerging. When i run the test code with my data. I encountered a IndexError that the actual index which was generated through the code "x,y,z = (pts[:,0]/gap).astype(np.int32)" was out of bounds for axis 1 with size of volume. I didnot change any code except training and testing with my data.  I am curious to know the the function of BlockMerging and the meaning of the following code:
            gap = 5e-3
            volume_num = int(1. / gap)+1+200
            volume = -1* np.ones([volume_num,volume_num,volume_num]).astype(np.int32)
            volume_seg = -1* np.ones([volume_num,volume_num,volume_num]).astype(np.int32)

Looking for you reply, Thank You!

**Comment by WXinlong** [comment]
Hi, the BlockMergeing part is borrowed from SGPN, as said in our paper. The code you mentioned aim to remove deplicate instances.

**Comment by swjtu-jia-wei** [comment]
您好，我也在blockmerging这里出现了问题。不同的是我用的都是S3DIS数据以及训练好的model，
但还是出现了   index 129 is out of bounds for axis 0 with size 100这个问题，请问您解决了吗？
