### ISSUE TITLE
irregular performance with 6-fold CV

### ISSUE THREAD

**Issue by NaNaoiSong** [WXinlong/ASIS#21]
hi Xinlong,
thanks for your work. when I use 6-fold CV with S3DIS dataset, there is an irregular performance. could you please provide the performance of each fold ?  thanks.

**Comment by WXinlong** [comment]
Hi, now I don't have results on each fold except the fold 5. What's your results on 6-fold and area 5?

**Comment by NaNaoiSong** [comment]
Thanks, I have solved it.  I made a training mistake.
