### ISSUE TITLE
tf_op compile failed on tf1.3

### ISSUE THREAD

**Issue by renhaha123** [WXinlong/ASIS#23]
Thank you for your great code! 
I used the "conda install --channel https://conda.anaconda.org/anaconda tensorflow-gpu=1.3.0" command to install tf1.3, but there is no " external/nsync/public"  behind "anaconda3/envs/py2.7/lib/python2.7/site-packages/tensorflow/include/external/" in the directory. 
Thus I can't compile successfully tf_op. 
Any advise will be appreciated.

**Comment by renhaha123** [comment]
>

**Comment by mohuamuyu** [comment]
tf1.4 have " external/nsync/public" behind "anaconda3/envs/py2.7/lib/python2.7/site-packages/tensorflow/include/external/"

**Comment by renhaha123** [comment]
Thanks for your advice.
However,the author suggest to use tf1.3 , we can reproduce the paper's result.
