### ISSUE TITLE
bug in collect_indoor3d_data.py

### ISSUE THREAD

**Issue by PeterPyPan** [WXinlong/ASIS#26]
There is a bug in the data collection script (`collect_indoor3d_data.py`) for windows systems, resulting in wrongly placed, npy files.

Line 18 does not split the path into all its components as the separator on windows is `\\`. 
The result of this bug is that the processed npy files end up in the `Stanford3dDataset` folder, instead of the `stanford_indoor3d_ins.sem` folder.

```
>>> elements = anno_path.split('/')
elements = ['C:\\ASIS\\data\\Stanford3dDataset_v1.2_Aligned_Version\\Area_2', 'conferenceRoom_1', 'Annotations']
```

minimal fix tested on windows:
```
>>> elements = os.path.normpath(anno_path).split(os.path.sep)
elements = ['C:', 'ASIS', 'data', 'Stanford3dDataset_v1.2_Aligned_Version', 'Area_2', 'conferenceRoom_1', 'Annotations']
```

**Comment by WXinlong** [comment]
Hi Peter, thanks for pointing out this.:)
