### ISSUE TITLE
python 3 fix for indoor3d_util.py

### ISSUE THREAD

**Issue by PeterPyPan** [WXinlong/ASIS#27]
In python 3 it is not allowed to use the `+` operator on a range object and a list.
This causes an error in `indoor3d_util.py` (sample_data(), line 129) when running the `gen_h5.py` script.

Minimal fix for python 3 compatibility:
```
>>> return np.concatenate([data, dup_data], 0), range(N)+list(sample)
TypeError: unsupported operand type(s) for +: 'range' and 'list'
>>> return np.concatenate([data, dup_data], 0), list(range(N))+list(sample)
this works
```

**Comment by WXinlong** [comment]
Hi, we follow the SGPN for the data processing part and use the same indoor3d_util.py file.  
Thank you for pointing out this and it could be helpful for others using python3.
