### ISSUE TITLE
Could you please provide the δv and δd for outdoor dataset?

### ISSUE THREAD

**Issue by xbb2017** [WXinlong/ASIS#31]
Thanks for your great code. Could you please provide the value of δv and δd for outdoor dataset? (https://github.com/WXinlong/ASIS/blob/master/misc/vkitti_asis.png) Thanks a lot.

**Comment by WXinlong** [comment]
Hi, thanks for your interest.:) 
The δv and δd both are not modified on vkitti dataset, which are still 0.5 and 1.5.
