### ISSUE TITLE
A issue on block merging

### ISSUE THREAD

**Issue by PatrickFeng** [WXinlong/ASIS#40]
Thank you @WXinlong for your excellent work.

I noticed that you used try...except... in function **BlockMerging()** when assigning value to the ndarray _overlapgroupcounts_. I also found this function in SGPN repo. When I test Area 5 Hallway 1 of S3DIS with SGPN, there is a error in this line **"overlapgroupcounts[grouplabel[i],volume[xx,yy,zz]] += 1"** that reports the index exceeds array index range(300).
Did you meet this error either and add a try...except... syntax here?

**Comment by swjtu-jia-wei** [comment]
Hi, I have the same problem as you now. Did you solve it?

**Comment by PatrickFeng** [comment]
> 

It's too long and I have forgotten how to solve it. My disk was down once and all data and code were lost.

I guess this error is insignificant since @WXinlong workaround it with try...except... and it works.
