### ISSUE TITLE
Prepared HDF5 data for training: broken link

### ISSUE THREAD

**Issue by valvador92** [WXinlong/ASIS#5]
I would like to download the prepared HDF5 data for training but the link doesn't work. Could you fix it?

Do you have a link to download raw S3DIS data?

Thank you

**Comment by WXinlong** [comment]
Hi,  you can download the raw S3DIS dataset through [this form.](https://docs.google.com/forms/d/e/1FAIpQLScDimvNMCGhy_rmBA2gHfDu3naktRm6A8BPwAWWDv-Uhm6Shw/viewform?c=0&w=1)
The README will be updated.
