### ISSUE TITLE
pretrained model belongs to which log

### ISSUE THREAD

**Issue by iris0329** [WXinlong/ASIS#6]
Hi !
In `test.py`, how to match your pretrained model with the arg:
```
--model_path
log1/epoch_99.ckpt
```
I mean the pretrained model belongs to which log ?

Thanks for help ！

**Comment by WXinlong** [comment]
@iris0329  Hi, you can directly set --model_path to the path of your downloaded model. Or, put it under log5/, and set --model_path log5/epoch_99.ckpt. 
The line 4 of train.sh can be used as a reference:)

**Comment by iris0329** [comment]
Thank you
