### ISSUE TITLE
6-fold CV

### ISSUE THREAD

**Issue by Biotan** [WXinlong/ASIS#8]
hi,thanks for your excellent work.there is a problem that I meet when I use 6-fold CV,but I get a irregular performance,I think there is some bug in my code,could you please  give me your code with 6-fold CV ? if it's possible,could you please give me the code with shapeNet dataset ? thanks a lot.

**Comment by WXinlong** [comment]
@Biotan Hi, you can modify the line 8 of eval_iou_accuracy.py for 6-fold CV: 
`for i in range(1,7):`

**Comment by Biotan** [comment]
thanks for your answers.
In addition, I want to verify whether the knn is needed in inference step,I find that in test, knn is needed.however,when you calculate the inference time ,knn is removed.

**Comment by WXinlong** [comment]
@Biotan  Hi, kNN is needed. It is not removed during inference.
