### ISSUE TITLE
error in tfop compling

### ISSUE THREAD

**Issue by justbin1123** [WXinlong/ASIS#9]
![截图](https://user-images.githubusercontent.com/38319058/57913872-1ac9d680-78c0-11e9-89dc-aaddceb4b2e8.PNG)
I get the error "not find -ltensorflow_framework
"when i try to complie on may os

if i try use ur tf_sampling_so.so,I get the error "tf_sampling_so.so: undefined symbol: _ZN10tensorflow15OpKernelContext10CtxFailureEPKciRKNS_6StatusE"

And my env is tf1.4 py27 cuda9.0.

**Comment by GuoliangShiIntel** [comment]
Hello, I get the same error.

tf_sampling_so.so: undefined symbol: 
_ZN10tensorflow6StatusC1ENS_5error4CodeENS_11StringPieceE

My environment is tf1.13 py3.6 cuda9.0. 

Have you solved this problem?

**Comment by GuoliangShiIntel** [comment]
I find how to resolve this problem in PointNet++.

https://github.com/charlesq34/pointnet2/issues/48

**Comment by justbin1123** [comment]
> I find how to resolve this problem in PointNet++.
> 
> [charlesq34/pointnet2#48](https://github.com/charlesq34/pointnet2/issues/48)

https://github.com/charlesq34/pointnet2/issues/48#issuecomment-458154518  ive resolve it
